#!/bin/bash

# Set directories
SRC_DIR="./social_media_scraper"
LIB_DIR="./social_media_scraper/libc"
LIB_NAME="sqlCImp.so"
SRC_FILE="$SRC_DIR/utils.c"

# Ensure the library directory exists
mkdir -p $LIB_DIR

# Compile utils.c into a shared library
echo "Building shared library for utils.c..."
gcc -shared -o $LIB_DIR/$LIB_NAME -fPIC $SRC_FILE -lsqlite3

# Check if the build was successful
if [ $? -eq 0 ]; then
    echo "Build successful. Shared library created at $LIB_DIR/$LIB_NAME"
else
    echo "Build failed. Check for errors in utils.c"
    exit 1
fi
